remote_theme: hydecorp/hydejack@v9.2.1
plugins:
  - jekyll-include-cache
  - jekyll-avatar
  - jekyll-seo-tag
  - jekyll-sitemap
accent_image: https://raw.githubusercontent.com/agkozak/zcomet-media/main/CometDonati.jpg
# favicon: /favicon.ico
# apple_touch_icon: /assets/img/logo.png
url: https://zcomet.io
title: zcomet
description: Fast, Simple Zsh Plugin Manager
github_username: agkozak
menu:
  - title: Documentation
    url: /documentation/
  - title: On GitHub
    url: https://github.com/agkozak/zcomet
author:
  name: Alexandros Kozak
  social:
    github: agkozak
hydejack:
  dark_mode:
    dynamic: true
    icon:    true
    always:  false
