remote_theme: hydecorp/hydejack@v9.1.4
plugins:
  - jekyll-include-cache
accent_image: https://raw.githubusercontent.com/agkozak/zcomet-media/main/CometDonati.jpg
favicon: /favicon.ico
apple_touch_icon: /assets/img/logo.png
